// Generated by CoffeeScript 1.3.1
(function() {
  var IStream, Instr, Module, Value;

  Module = {};

  IStream = (function() {

    IStream.name = 'IStream';

    function IStream(instrs, base) {
      if (base == null) {
        base = 0;
      }
      this.mStream = instrs;
      this.mDecoded = [];
      this.mIndex = base;
    }

    IStream.prototype.nextWord = function() {
      return this.mStream[this.mIndex++];
    };

    IStream.prototype.index = function(v) {
      if (v == null) {
        v = 0;
      }
      if (v) {
        return this.mIndex = v;
      } else {
        return this.mIndex;
      }
    };

    return IStream;

  })();

  Value = (function() {
    var _i, _j, _k, _ref, _ref1, _ref2, _results, _results1, _results2;

    Value.name = 'Value';

    _ref = (function() {
      _results = [];
      for (var _i = 0x0; 0x0 <= 0xa ? _i <= 0xa : _i >= 0xa; 0x0 <= 0xa ? _i++ : _i--){ _results.push(_i); }
      return _results;
    }).apply(this), Value.REG_A = _ref[0], Value.REG_B = _ref[1], Value.REG_C = _ref[2], Value.REG_X = _ref[3], Value.REG_Y = _ref[4], Value.REG_Z = _ref[5], Value.REG_I = _ref[6], Value.REG_J = _ref[7], Value.REG_PC = _ref[8], Value.REG_SP = _ref[9], Value.REG_O = _ref[10];

    _ref1 = (function() {
      _results1 = [];
      for (var _j = 0x18; 0x18 <= 0x1a ? _j <= 0x1a : _j >= 0x1a; 0x18 <= 0x1a ? _j++ : _j--){ _results1.push(_j); }
      return _results1;
    }).apply(this), Value.VAL_POP = _ref1[0], Value.VAL_PEEK = _ref1[1], Value.VAL_PUSH = _ref1[2];

    _ref2 = (function() {
      _results2 = [];
      for (var _k = 0x1b; 0x1b <= 0x1d ? _k <= 0x1d : _k >= 0x1d; 0x1b <= 0x1d ? _k++ : _k--){ _results2.push(_k); }
      return _results2;
    }).apply(this), Value.VAL_SP = _ref2[0], Value.VAL_PC = _ref2[1], Value.VAL_O = _ref2[2];

    function Value(stream, enc) {
      this.mIStream = stream;
      this.isMem = false;
      this.isReg = false;
      this.mEncoding = enc;
      this.mNext = 0;
      if ((0x00 <= enc && enc <= 0x07)) {
        this.isReg = true;
        this.mValue = enc;
      } else if ((0x08 <= enc && enc <= 0x0f)) {
        this.isMem = true;
      } else if ((0x10 <= enc && enc <= 0x17)) {
        this.isMem = true;
        this.mNext = this.mIStream.nextWord();
      } else if (enc === Value.VAL_POP) {
        "";

      } else if (enc === Value.VAL_PEEK) {
        "";

      } else if (enc === Value.VAL_PUSH) {
        "";

      } else if (enc === Value.VAL_SP) {
        this.isReg = true;
        this.mValue = Value.REG_SP;
      } else if (enc === Value.VAL_PC) {
        this.isReg = true;
        this.mValue = Value.REG_PC;
      } else if (enc === Value.VAL_O) {
        this.isReg = true;
        this.mValue = Value.REG_O;
      } else if (enc === 0x1e) {
        this.isMem = true;
        this.mNext = this.mIStream.nextWord();
        this.mValue = this.mNext;
      } else if (enc === 0x1f) {
        this.mNext = this.mIStream.nextWord();
        this.mValue = this.mNext;
      } else if ((0x20 <= enc && enc <= 0x3f)) {
        this.mValue = enc - 0x20;
      }
    }

    Value.prototype.get = function(cpu) {
      if (this.isMem) {
        return cpu.readMem(this.mValue);
      } else if (this.isReg) {
        return cpu.readReg(this.mValue);
      } else if (this.mEncoding === Value.VAL_POP) {
        return cpu.pop();
      } else if (this.mEncoding === Value.VAL_PUSH) {
        return console.log("ERROR: Trying to 'get' PUSH");
      } else if (this.mEncoding === Value.VAL_PEEK) {
        return cpu.peek();
      } else {
        return this.mValue;
      }
    };

    Value.prototype.set = function(cpu, val) {
      if (this.isMem) {
        return cpu.writeMem(this.mValue, val);
      } else if (this.isReg) {
        return cpu.writeReg(this.mValue, val);
      } else if (this.mEncoding === Value.VAL_POP) {
        return console.log("ERROR: Trying to 'set' POP");
      } else if (this.mEncoding === Value.VAL_PUSH) {
        return cpu.push(val);
      } else if (this.mEncoding === Value.VAL_PEEK) {
        return console.log("ERROR: Trying to 'set' PEEK");
      } else {
        return console.log("Error: Attempt to 'set' a literal value");
      }
    };

    Value.prototype.raw = function() {
      return this.mEncoding;
    };

    return Value;

  })();

  Instr = (function() {
    var _i, _ref, _ref1, _results;

    Instr.name = 'Instr';

    _ref = (function() {
      _results = [];
      for (var _i = 0x0; 0x0 <= 0xf ? _i <= 0xf : _i >= 0xf; 0x0 <= 0xf ? _i++ : _i--){ _results.push(_i); }
      return _results;
    }).apply(this), Instr.OPC_ADV = _ref[0], Instr.OPC_SET = _ref[1], Instr.OPC_ADD = _ref[2], Instr.OPC_SUB = _ref[3], Instr.OPC_MUL = _ref[4], Instr.OPC_DIV = _ref[5], Instr.OPC_MOD = _ref[6], Instr.OPC_SHL = _ref[7], Instr.OPC_SHR = _ref[8], Instr.OPC_AND = _ref[9], Instr.OPC_BOR = _ref[10], Instr.OPC_XOR = _ref[11], Instr.OPC_IFE = _ref[12], Instr.OPC_IFN = _ref[13], Instr.OPC_IFG = _ref[14], Instr.OPC_IFB = _ref[15];

    _ref1 = [0, 1], Instr.ADV_RSV = _ref1[0], Instr.ADV_JSR = _ref1[1];

    function Instr(stream) {
      var _ref2;
      this.mIStream = stream;
      this.mAddr = this.mIStream.index();
      _ref2 = this.decode(this.mIStream.nextWord()), this.mOpc = _ref2[0], this.mValA = _ref2[1], this.mValB = _ref2[2];
    }

    Instr.prototype.decode = function(instr) {
      var opcode, valA, valB;
      opcode = instr & this.OPCODE_MASK();
      valA = (instr & this.VALA_MASK()) >> 4;
      valB = (instr & this.VALB_MASK()) >> 10;
      return [opcode, new Value(this.mIStream, valA), new Value(this.mIStream, valB)];
    };

    Instr.prototype.opc = function() {
      return this.mOpc;
    };

    Instr.prototype.valA = function() {
      return this.mValA;
    };

    Instr.prototype.valB = function() {
      return this.mValB;
    };

    Instr.prototype.addr = function() {
      return this.mAddr;
    };

    Instr.prototype.OPCODE_MASK = function() {
      return 0x000f;
    };

    Instr.prototype.VALA_MASK = function() {
      return 0x03f0;
    };

    Instr.prototype.VALB_MASK = function() {
      return 0xfc00;
    };

    return Instr;

  })();

  exports.Value = Value;

  exports.Instr = Instr;

  exports.IStream = IStream;

}).call(this);
