// Generated by CoffeeScript 1.3.1
(function() {
  var Device, Module;

  Module = {};

  Device = (function() {

    Device.name = 'Device';

    function Device(name, cpu) {
      if (name == null) {
        name = "?";
      }
      this.mName = name;
      this.mCpu = cpu;
    }

    Device.prototype.id = function() {
      return 0;
    };

    Device.prototype.mfgr = function() {
      return 0;
    };

    Device.prototype.ver = function() {
      return 0;
    };

    Device.prototype.query = function() {
      return this.fromMfgrId(this.mfgr(), this.id(), this.ver());
    };

    Device.prototype.hwInterrupt = function() {
      return;
    };

    Device.prototype.interrupt = function(m) {
      return;
    };

    Device.prototype.mapMemory = function(base, len) {
      return;
    };

    Device.prototype.unmapMemory = function(base) {
      return;
    };

    Device.prototype.fromMfgrId = function(mfgr, id, ver) {
      this.mCpu.regA(id & 0xffff);
      this.mCpu.regB((id >> 16) & 0xffff);
      this.mCpu.regC(ver);
      this.mCpu.regX(mfgr & 0xffff);
      return this.mCpu.regY((mfgr >> 16) & 0xffff);
    };

    return Device;

  })();

  exports.Device = Device;

}).call(this);
