// Generated by CoffeeScript 1.3.3
(function() {
  var Device, Hmd2043, Hmu1440, Module, device,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Module = {};

  device = require("./device");

  Device = device.Device;

  Hmd2043 = (function(_super) {

    __extends(Hmd2043, _super);

    function Hmd2043(cpu) {
      Hmd2043.__super__.constructor.call(this, "HMD2043", cpu);
    }

    Hmd2043.prototype.id = function() {
      return 0x74fa4cae;
    };

    Hmd2043.prototype.mfgr = function() {
      return 0x21544948;
    };

    Hmd2043.prototype.ver = function() {
      return 0x07c2;
    };

    Hmd2043.prototype.hwInterrupt = function() {
      switch (this.mCpu.regA()) {
        case 0x0000:
          return this.queryMediaPresent();
        case 0x0001:
          return this.queryMediaParameters();
        case 0x0002:
          return this.queryDeviceFlags();
        case 0x0003:
          return this.updateDeviceFlags();
        case 0x0004:
          return this.queryInterruptType();
        case 0x0005:
          return this.setInterruptMessage();
        case 0x0010:
          return this.readSectors();
        case 0x0011:
          return this.writeSectors();
        case 0xffff:
          return this.queryMediaQuality();
        default:
          return void 0;
      }
    };

    Hmd2043.prototype.queryMediaPresent = function() {
      return void 0;
    };

    Hmd2043.prototype.queryMediaParameters = function() {
      return void 0;
    };

    Hmd2043.prototype.queryDeviceFlags = function() {
      return void 0;
    };

    Hmd2043.prototype.updateDeviceFlags = function() {
      return void 0;
    };

    Hmd2043.prototype.queryInterruptType = function() {
      return void 0;
    };

    Hmd2043.prototype.setInterruptMessage = function() {
      return void 0;
    };

    Hmd2043.prototype.readSectors = function() {
      return void 0;
    };

    Hmd2043.prototype.writeSectors = function() {
      return void 0;
    };

    Hmd2043.prototype.queryMediaQuality = function() {
      return void 0;
    };

    return Hmd2043;

  })(Device);

  Hmu1440 = (function() {

    function Hmu1440() {
      void 0;
    }

    return Hmu1440;

  })();

}).call(this);
