// Generated by CoffeeScript 1.3.1
(function() {
  var Device, Lem1802, Module, device,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  Module = {};

  device = require("./device");

  Device = device.Device;

  Lem1802 = (function(_super) {

    __extends(Lem1802, _super);

    Lem1802.name = 'Lem1802';

    function Lem1802(cpu, canvas) {
      if (canvas == null) {
        canvas = void 0;
      }
      Lem1802.__super__.constructor.call(this, "LEM1802", cpu);
      this.mCanvas = canvas;
      this.mCtx = canvas != null ? canvas.getContext('2d') : void 0;
      this.mScale = 4;
      this.mScreenAddr = 0;
      this.mFontAddr = 0;
      this.mPaletteAddr = 0;
      this.mScreen = void 0;
      this.mUserFont = void 0;
      this.mUserPalette = void 0;
      this.clear();
    }

    Lem1802.prototype.id = function() {
      return 0x7349f615;
    };

    Lem1802.prototype.mfgr = function() {
      return 0x1c6c8b38;
    };

    Lem1802.prototype.ver = function() {
      return 0x1802;
    };

    Lem1802.prototype.hwInterrupt = function() {
      switch (this.mCpu.regA()) {
        case 0:
          return this.memMapScreen();
        case 1:
          return this.memMapFont();
        case 2:
          return this.memMapPalette();
        case 3:
          return this.setBorderColor();
        default:
          return;
      }
    };

    Lem1802.prototype.memMapScreen = function() {
      var base, _;
      base = this.mCpu.regB();
      if (base === 0) {
        this.unmapMemory(this.mScreenAddr);
        this.mScreen = void 0;
      } else {
        this.mapMemory(base, this.VID_RAM_SIZE, this._screenCB());
        this.mScreen = (function() {
          var _i, _ref, _results;
          _results = [];
          for (_ = _i = 0, _ref = this.VID_RAM_SIZE; 0 <= _ref ? _i <= _ref : _i >= _ref; _ = 0 <= _ref ? ++_i : --_i) {
            _results.push(0);
          }
          return _results;
        }).call(this);
      }
      return this.mScreenAddr = base;
    };

    Lem1802.prototype.memMapFont = function() {
      var base, _;
      base = this.mCpu.regB();
      if (base === 0) {
        this.unmapMemory(this.mFontAddr);
        this.mUserFont = void 0;
      } else {
        this.mapMemory(base, this.FONT_RAM_SIZE, this._fontCB());
        this.mUserFont = (function() {
          var _i, _ref, _results;
          _results = [];
          for (_ = _i = 0, _ref = this.FONT_RAM_SIZE; 0 <= _ref ? _i <= _ref : _i >= _ref; _ = 0 <= _ref ? ++_i : --_i) {
            _results.push(0);
          }
          return _results;
        }).call(this);
      }
      return this.mFontAddr = base;
    };

    Lem1802.prototype.memMapPalette = function() {
      var base, _;
      base = this.mCpu.regB();
      if (base === 0) {
        this.unmapMemory(this.mPaletteAddr);
        this.mUserPalette = void 0;
      } else {
        this.mapMemory(base, this.PALETTE_RAM_SIZE, this._paletteCB());
        this.mUserPalette = (function() {
          var _i, _ref, _results;
          _results = [];
          for (_ = _i = 0, _ref = this.PALETTE_RAM_SIZE; 0 <= _ref ? _i <= _ref : _i >= _ref; _ = 0 <= _ref ? ++_i : --_i) {
            _results.push(0);
          }
          return _results;
        }).call(this);
      }
      return this.mPaletteAddr = base;
    };

    Lem1802.prototype.setBorderColor = function() {
      return;
    };

    Lem1802.prototype.readFontRam = function(i) {
      return Lem1802.DFL_FONT[i];
    };

    Lem1802.prototype.readPaletteRam = function(i) {
      var b, g, r, word;
      word = Lem1802.DFL_PALETTE[i];
      b = word & 0xf;
      g = (word >> 4) & 0xf;
      r = (word >> 8) & 0xf;
      return {
        r: r,
        g: g,
        b: b
      };
    };

    Lem1802.prototype.rgbString = function(c) {
      return "rgb(" + (c.r * 16) + ", " + (c.g * 16) + ", " + (c.b * 16) + ")";
    };

    Lem1802.prototype.getChar = function(c) {
      return [this.readFontRam(c * 2), this.readFontRam(c * 2 + 1)];
    };

    Lem1802.prototype.drawChar = function(x, y, c) {
      var bg, bit, fg, i, word, x_, y_, _i, _results;
      if (!(this.mCtx != null)) {
        return;
      }
      bg = (c >> 8) & 0xf;
      fg = (c >> 12) & 0xf;
      c = c & 0x7f;
      x = x * 4;
      y = y * 8;
      c = this.getChar(c);
      this.mCtx.fillStyle = this.rgbString(this.readPaletteRam(bg));
      this.mCtx.fillRect(x * this.mScale, y * this.mScale, 4 * this.mScale, 8 * this.mScale);
      this.mCtx.fillStyle = this.rgbString(this.readPaletteRam(fg));
      _results = [];
      for (i = _i = 31; _i >= 0; i = --_i) {
        word = Math.floor(i / 16);
        bit = i % 16;
        if (c[1 - word] & (1 << bit)) {
          x_ = x + 3 - Math.floor(i / 8);
          y_ = y + (i % 8);
          _results.push(this.mCtx.fillRect(x_ * this.mScale, y_ * this.mScale, this.mScale, this.mScale));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    Lem1802.prototype.clear = function() {
      if (!(this.mCtx != null)) {
        return;
      }
      this.mCtx.fillStyle = this.rgbString(this.readPaletteRam(0xf));
      return this.mCtx.fillRect(0, 0, 128 * this.mScale, 96 * this.mScale);
    };

    Lem1802.prototype._screenCB = function() {
      var lem;
      lem = this;
      return function(a, v) {
        var x, y;
        console.log("Screen CB");
        x = a % 32;
        y = Math.floor(a / 32);
        return lem.drawChar(x, y, v);
      };
    };

    Lem1802.prototype._fontCB = function() {
      var lem;
      lem = this;
      return function(a, v) {
        return console.log("Font CB");
      };
    };

    Lem1802.prototype._paletteCB = function() {
      var lem;
      lem = this;
      return function(a, v) {
        return console.log("Palette CB");
      };
    };

    Lem1802.prototype.VID_RAM_SIZE = 386;

    Lem1802.prototype.FONT_RAM_SIZE = 256;

    Lem1802.prototype.PALETTE_RAM_SIZE = 16;

    Lem1802.DFL_FONT = [0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x00ff, 0x8100, 0x0, 0x0, 0x0, 0x0, 0xff09, 0x0900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff18, 0x6681, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff80, 0x80ff, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x00ff, 0x8100, 0x0, 0x0, 0x0, 0x0, 0xff09, 0x0900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff18, 0x6681, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xff80, 0x80ff, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0];

    Lem1802.DFL_PALETTE = [0x0fff, 0x0ff0, 0x0f0f, 0x0f00, 0x0ccc, 0x0888, 0x0880, 0x0808, 0x0800, 0x00ff, 0x00f0, 0x0088, 0x0080, 0x000f, 0x0008, 0x0000];

    return Lem1802;

  })(Device);

  exports.Lem1802 = Lem1802;

}).call(this);
