// Generated by CoffeeScript 1.3.1
(function() {
  var Device, Lem1802, Module,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor; child.__super__ = parent.prototype; return child; };

  Module = {};

  Device = require("./device").Device;

  Lem1802 = (function(_super) {

    __extends(Lem1802, _super);

    Lem1802.name = 'Lem1802';

    function Lem1802(cpu, canvas) {
      if (canvas == null) {
        canvas = void 0;
      }
      Lem1802.__super__.constructor.call(this, "LEM1802", cpu);
      this.mCanvas = canvas;
      this.mCtx = canvas != null ? canvas.getContext('2d') : void 0;
      this.mScale = 4;
      this.mScreenAddr = 0;
      this.mFontAddr = 0;
      this.mPaletteAddr = 0;
      this.mScreen = void 0;
      this.mUserFont = void 0;
      this.mUserPalette = void 0;
      this.mBorderColor = 4;
      this.clear();
      this.drawBorder(this.mBorderColor);
    }

    Lem1802.prototype.id = function() {
      return 0x7349f615;
    };

    Lem1802.prototype.mfgr = function() {
      return 0x1c6c8b38;
    };

    Lem1802.prototype.ver = function() {
      return 0x1802;
    };

    Lem1802.prototype.hwInterrupt = function() {
      switch (this.mCpu.regA()) {
        case 0:
          return this.memMapScreen();
        case 1:
          return this.memMapFont();
        case 2:
          return this.memMapPalette();
        case 3:
          return this.setBorderColor();
        default:
          return;
      }
    };

    Lem1802.prototype.reset = function() {
      this.mScreen = void 0;
      this.mScreenAddr = 0;
      this.mUserFont = void 0;
      this.mFontAddr = 0;
      this.mUserPalette = void 0;
      this.mPaletteAddr = 0;
      return this.clear();
    };

    Lem1802.prototype.memMapScreen = function() {
      var base, _;
      base = this.mCpu.regB();
      if (base === 0) {
        this.unmapMemory(this.mScreenAddr);
        this.mScreen = void 0;
      } else {
        this.mapMemory(base, this.VID_RAM_SIZE, this._screenCB());
        this.mScreen = (function() {
          var _i, _ref, _results;
          _results = [];
          for (_ = _i = 0, _ref = this.VID_RAM_SIZE; 0 <= _ref ? _i <= _ref : _i >= _ref; _ = 0 <= _ref ? ++_i : --_i) {
            _results.push(0);
          }
          return _results;
        }).call(this);
      }
      return this.mScreenAddr = base;
    };

    Lem1802.prototype.memMapFont = function() {
      var base, _;
      base = this.mCpu.regB();
      if (base === 0) {
        this.unmapMemory(this.mFontAddr);
        this.mUserFont = void 0;
      } else {
        this.mapMemory(base, this.FONT_RAM_SIZE, this._fontCB());
        this.mUserFont = (function() {
          var _i, _ref, _results;
          _results = [];
          for (_ = _i = 0, _ref = this.FONT_RAM_SIZE; 0 <= _ref ? _i <= _ref : _i >= _ref; _ = 0 <= _ref ? ++_i : --_i) {
            _results.push(0);
          }
          return _results;
        }).call(this);
      }
      return this.mFontAddr = base;
    };

    Lem1802.prototype.memMapPalette = function() {
      var base, _;
      base = this.mCpu.regB();
      if (base === 0) {
        this.unmapMemory(this.mPaletteAddr);
        this.mUserPalette = void 0;
      } else {
        this.mapMemory(base, this.PALETTE_RAM_SIZE, this._paletteCB());
        this.mUserPalette = (function() {
          var _i, _ref, _results;
          _results = [];
          for (_ = _i = 0, _ref = this.PALETTE_RAM_SIZE; 0 <= _ref ? _i <= _ref : _i >= _ref; _ = 0 <= _ref ? ++_i : --_i) {
            _results.push(0);
          }
          return _results;
        }).call(this);
      }
      return this.mPaletteAddr = base;
    };

    Lem1802.prototype.setBorderColor = function() {
      return this.drawBorder(this.mBorderColor = this.mCpu.regB() & 0xf);
    };

    Lem1802.prototype.readFontRam = function(i) {
      if (this.mFont != null) {
        return this.mFont[i];
      } else {
        return Lem1802.DFL_FONT[i];
      }
    };

    Lem1802.prototype.readPaletteRam = function(i) {
      var b, g, r, word;
      word = Lem1802.DFL_PALETTE[i];
      b = word & 0xf;
      g = (word >> 4) & 0xf;
      r = (word >> 8) & 0xf;
      return {
        r: r,
        g: g,
        b: b
      };
    };

    Lem1802.prototype.rgbString = function(c) {
      return "rgb(" + (c.r * 16) + ", " + (c.g * 16) + ", " + (c.b * 16) + ")";
    };

    Lem1802.prototype.getChar = function(c) {
      return [this.readFontRam(c * 2), this.readFontRam(c * 2 + 1)];
    };

    Lem1802.prototype.drawChar = function(x, y, c) {
      var bg, bit, fg, i, word, x_, y_, _i, _results;
      if (!(this.mCtx != null)) {
        return;
      }
      bg = (c >> 8) & 0xf;
      fg = (c >> 12) & 0xf;
      c = c & 0x7f;
      x = x * 4;
      y = y * 8;
      c = this.getChar(c);
      this.mCtx.fillStyle = this.rgbString(this.readPaletteRam(bg));
      this.mCtx.fillRect(x * this.mScale, y * this.mScale, 4 * this.mScale, 8 * this.mScale);
      this.mCtx.fillStyle = this.rgbString(this.readPaletteRam(fg));
      _results = [];
      for (i = _i = 31; _i >= 0; i = --_i) {
        word = Math.floor(i / 16);
        bit = i % 16;
        if (c[1 - word] & (1 << bit)) {
          x_ = x + 3 - Math.floor(i / 8);
          y_ = y + (i % 8);
          _results.push(this.mCtx.fillRect(x_ * this.mScale, y_ * this.mScale, this.mScale, this.mScale));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    Lem1802.prototype.drawBorder = function(c) {
      var x, y, _i, _j, _ref, _ref1, _results;
      c = c << 8;
      for (x = _i = 0, _ref = this.WIDTH + 1; 0 <= _ref ? _i <= _ref : _i >= _ref; x = 0 <= _ref ? ++_i : --_i) {
        this.drawChar(x, 0, c);
        this.drawChar(x, this.HEIGHT + 1, c);
      }
      _results = [];
      for (y = _j = 0, _ref1 = this.HEIGHT + 1; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; y = 0 <= _ref1 ? ++_j : --_j) {
        this.drawChar(0, y, c);
        _results.push(this.drawChar(this.WIDTH + 1, y, c));
      }
      return _results;
    };

    Lem1802.prototype.clear = function() {
      if (!(this.mCtx != null)) {
        return;
      }
      this.mCtx.fillStyle = this.rgbString(this.readPaletteRam(0xf));
      this.mCtx.fillRect(0, 0, (this.WIDTH + 2) * 4 * this.mScale, (this.HEIGHT + 2) * 8 * this.mScale);
      return this.drawBorder();
    };

    Lem1802.prototype.redraw = function() {
      var i, x, y, _i, _ref, _results;
      _results = [];
      for (x = _i = 0, _ref = this.WIDTH; 0 <= _ref ? _i <= _ref : _i >= _ref; x = 0 <= _ref ? ++_i : --_i) {
        _results.push((function() {
          var _j, _ref1, _results1;
          _results1 = [];
          for (y = _j = 0, _ref1 = this.HEIGHT; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; y = 0 <= _ref1 ? ++_j : --_j) {
            i = y * this.WIDTH + x;
            if (this.mScreen[i]) {
              _results1.push(this.drawChar(x + 1, y + 1, this.mScreen[i]));
            } else {
              _results1.push(void 0);
            }
          }
          return _results1;
        }).call(this));
      }
      return _results;
    };

    Lem1802.prototype._screenCB = function() {
      var lem;
      lem = this;
      return function(a, v) {
        lem.mScreen[a] = v;
        return lem.redraw();
      };
    };

    Lem1802.prototype._fontCB = function() {
      var lem;
      lem = this;
      return function(a, v) {
        lem.mFont[a] = v;
        return lem.redraw();
      };
    };

    Lem1802.prototype._paletteCB = function() {
      var lem;
      lem = this;
      return function(a, v) {
        lem.mPalette[a] = v;
        return lem.redraw();
      };
    };

    Lem1802.prototype.VID_RAM_SIZE = 386;

    Lem1802.prototype.FONT_RAM_SIZE = 256;

    Lem1802.prototype.PALETTE_RAM_SIZE = 16;

    Lem1802.prototype.WIDTH = 32;

    Lem1802.prototype.HEIGHT = 12;

    Lem1802.prototype.BORDER_SIZE = 12;

    Lem1802.DFL_FONT = [0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0000, 0x0000, 0x00be, 0x0000, 0x0600, 0x0600, 0xfe24, 0xfe00, 0x48fe, 0x2400, 0xe410, 0x4e00, 0x2070, 0x2000, 0x0006, 0x0000, 0x3844, 0x8200, 0x8244, 0x3800, 0x1408, 0x1400, 0x2070, 0x2000, 0x80c0, 0x0000, 0x1010, 0x1000, 0x0080, 0x0000, 0xc038, 0x0600, 0xfe82, 0xfe00, 0x82fe, 0x8000, 0xf292, 0x9e00, 0x9292, 0xfe00, 0x1e10, 0xfe00, 0x9e92, 0xf200, 0xfe92, 0xf200, 0x0202, 0xfe00, 0xfe92, 0xfe00, 0x9e92, 0xfe00, 0x0088, 0x0000, 0x80c8, 0x0000, 0x2050, 0x8800, 0x2828, 0x2800, 0x8850, 0x2000, 0x04b2, 0x0c00, 0x70a8, 0x7000, 0xfc12, 0xfc00, 0xfe92, 0x6c00, 0x7c82, 0x4400, 0xfe82, 0x7c00, 0xfe92, 0x9200, 0xfe12, 0x1200, 0x7c82, 0xe400, 0xfe10, 0xfe00, 0x82fe, 0x8200, 0x4080, 0x7e00, 0xfe18, 0xe600, 0xfe80, 0x8000, 0xfe0c, 0xfe00, 0xfe3c, 0xfe00, 0x7c82, 0x7c00, 0xfe12, 0x0c00, 0x7c82, 0xfc00, 0xfe12, 0xec00, 0x4c92, 0x6400, 0x02fe, 0x0200, 0xfe80, 0xfe00, 0x7e80, 0x7e00, 0xfe60, 0xfe00, 0xee10, 0xee00, 0x0ef0, 0x0e00, 0xe292, 0x8e00, 0x00fe, 0x8200, 0x0638, 0xc000, 0x0082, 0xfe00, 0x0402, 0x0400, 0x8080, 0x8080, 0x0002, 0x0400, 0x48a8, 0xf800, 0xfc90, 0x6000, 0x7088, 0x5000, 0x6090, 0xfc00, 0x70a8, 0xb000, 0x20fc, 0x2400, 0xb8a8, 0xf800, 0xfc20, 0xe000, 0x90f4, 0x8000, 0xc090, 0xf400, 0xfc20, 0xd800, 0x04fc, 0x8000, 0xf830, 0xf800, 0xf808, 0xf800, 0x7088, 0x7000, 0xf828, 0x3800, 0x3828, 0xf800, 0xf808, 0x1800, 0xb8a8, 0xe800, 0x10fc, 0x9000, 0xf880, 0xf800, 0x7880, 0x7800, 0xf860, 0xf800, 0xd820, 0xd800, 0x98a0, 0x7800, 0xc8a8, 0x9800, 0x10ee, 0x8200, 0x00fe, 0x0000, 0x82ee, 0x1000, 0x1008, 0x1008, 0x0, 0x0];

    Lem1802.DFL_PALETTE = [0x0fff, 0x0ff0, 0x0f0f, 0x0f00, 0x0ccc, 0x0888, 0x0880, 0x0808, 0x0800, 0x00ff, 0x00f0, 0x0088, 0x0080, 0x000f, 0x0008, 0x0000];

    return Lem1802;

  })(Device);

  exports.Lem1802 = Lem1802;

}).call(this);
